config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
name = 'home'
urlpatterns = [
    path('home', views.home_page_view, name='home'),
    path('competencias', views.competencias, name='competencias'),
    path('formacao', views.formacao, name='formacao'),
    path('projetos', views.projetos, name='projetos'),
    path('quizz', views.quizzPage, name='quizz'),
    path('blog', views.blog, name='blog'),
    path('about', views.about, name='about'),
    path('nova', views.nova_post_view, name='nova'),
    path('edita/<int:Post_id>', views.edita_post_view, name='edita'),
    path('apaga/<int:Post_id>', views.apaga_post_view, name='apaga'),
    path('login', views.loginSite, name='login'),
    path('logout', views.logoutSite, name='logout'),
    path('web', views.web, name='web'),
    path('api', views.APIs, name='api'),
    path('projetoFinalDeCurso', views.projetoFinalDeCurso, name='projetoFinalDeCurso'),

    path('', views.home_page_view),

]

portfolio/models.py
from django.db import models


# Create your models here.


class Post(models.Model):
    titulo = models.CharField(max_length=200)
    descrição = models.CharField(max_length=500)
    prioridade = models.IntegerField(default=1)
    concluido = models.BooleanField(default=False)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo[:200]

    class Meta:
        ordering = ['-prioridade']


class Quizz(models.Model):
    nome = models.CharField(max_length=200)
    pergunta1 = models.CharField(max_length=200)
    pergunta2 = models.CharField(max_length=200)
    pergunta3 = models.CharField(max_length=200)
    pergunta4 = models.CharField(max_length=200)

    def __str__(self):
        return self.nome[:200]


class Pessoas(models.Model):
    nome = models.CharField(max_length=200)
    link = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.nome[:200]


def resolution_path(instance, filename):
    return f'users/{instance.id}/'


class Projetos(models.Model):
    nome = models.CharField(max_length=200)
    descrição = models.CharField(max_length=500)
    ano = models.IntegerField(default=0)
    git = models.CharField(max_length=200, null=True, blank=True)
    alunos = models.ManyToManyField(Pessoas)
    imagem = models.ImageField(upload_to='media/', null=True, blank=True)
    imagem2 = models.URLField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.nome[:200]


    class Meta:
        ordering = ['-imagem']


class Cadeira(models.Model):
    nome = models.CharField(max_length=200)
    ano = models.IntegerField(default=0)
    semestre = models.IntegerField(default=0)
    creditos = models.IntegerField(default=0)
    professores = models.ManyToManyField(Pessoas, related_name='cadeiras')
    rank = models.IntegerField(default=0)
    link = models.CharField(max_length=200)
    projetos = models.OneToOneField(Projetos, blank=True, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nome[:200]


class Tecnologias(models.Model):
    nome = models.CharField(max_length=200)
    acrónimo = models.CharField(max_length=5)
    ano = models.IntegerField(default=0)
    logotipo = models.ImageField(upload_to='media/', null=True, blank=True)
    descrição = models.CharField(max_length=5000)

    def __str__(self):
        return self.nome[:200]


class Tecnologias2(models.Model):
    nome = models.CharField(max_length=200)
    acrónimo = models.CharField(max_length=5)
    ano = models.IntegerField(default=0)
    logotipo = models.ImageField(upload_to='media/', null=True, blank=True)
    logotipo2 = models.URLField(max_length=500, null=True, blank=True)
    descrição = models.CharField(max_length=5000)

    def __str__(self):
        return self.nome[:200]



class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    numero = models.IntegerField(default=0)
    descrição = models.CharField(max_length=50000)
    link = models.CharField(max_length=2000)
    imagem = models.ImageField(upload_to='media/', null=True, blank=True)
    imagem2 = models.URLField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.titulo[:200]

class ProjetoFinalDeCurso(models.Model):
    autores = models.ManyToManyField(Pessoas, related_name="autores")
    orientadores = models.ManyToManyField(Pessoas, related_name="orientadores")
    ano = models.IntegerField(default=0)
    titulo = models.CharField(max_length=2000)
    resumo = models.CharField(max_length=200000)
    imagem = models.ImageField(upload_to='media/', null=True, blank=True)
    imagem2 = models.URLField(max_length=500, null=True, blank=True)
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.titulo[:200]

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post
from .models import Quizz


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição da tarefa...'}),
            'prioridade': forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1}),
        }


    # texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Título',
            'concluido': 'Concluída',
        }


    # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'prioridade': 'prioridade: baixa=1, media=2, alta=3',
        }


class QuizzForm(ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'introduza o seu nome ...'}),
        }


    # texto a exibir junto à janela de inserção
        labels = {
            'nome': 'Qual o seu nome',
            'pergunta1': 'Qual a ferramente responsável pela estilização de uma página web',
            'pergunta2': 'Em que ano foi criado o django',
            'pergunta3': 'Qual a linguagem de programação utilizada no django',
            'pergunta4': 'Que outra linguagem de programação é usada na criação de uma web pag',
        }

portfolio/views.py
import requests
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import PostForm
from .forms import QuizzForm
from .models import Post
from .models import Quizz
from .models import Projetos
from .models import Cadeira
from .models import Noticia
from .models import Tecnologias2
from .models import ProjetoFinalDeCurso

from .quizz import desenha_graficodados


def home_page_view(request):
    return render(request, 'portfolio/home.html')

def competencias(request):
    return render(request, 'portfolio/competencias.html')

def web(request):
    context = {'noticias': Noticia.objects.all(), 'tecnologias': Tecnologias2.objects.all()}
    return render(request, 'portfolio/web.html', context)

def formacao(request):
    context = {'cadeiras': Cadeira.objects.all()}
    return render(request, 'portfolio/formacao.html', context)

def projetos(request):
    context = {'projetos': Projetos.objects.all()}
    return render(request, 'portfolio/projetos.html', context)

def about(request):
    return render(request, 'portfolio/about.html')

def blog(request):
    context = {'post': Post.objects.all()}
    return render(request, 'portfolio/blog.html', context)


def quizzPage(request):
    desenha_graficodados(Quizz.objects.all())
    quizz = QuizzForm(request.POST, use_required_attribute=False)
    if quizz.is_valid():
        quizz.save()
        return HttpResponseRedirect(request.path_info)

    context = {'form': quizz}

    return render(request, 'portfolio/quizz.html', context)

def nova_post_view(request):

    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}

    return render(request, 'portfolio/nova.html', context)

def edita_post_view(request, Post_id):

    post = Post.objects.get(id=Post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'Post_id': Post_id}
    return render(request, 'portfolio/edita.html', context)


def apaga_post_view(request, Post_id):
    Post.objects.get(id=Post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))


def loginSite(request):
    if request.method == "POST":
        nome = request.POST.get('username')
        password = request.POST.get('password')
        utilizador = authenticate(request, username=nome, password=password)

        if utilizador is not None:
            login(request, utilizador)
            context = {'post': Post.objects.all()}
            return render(request, 'portfolio/blog.html', context)
        else:
            return render(
                request, 'portfolio/login.html',
                {'message': "Dados inválidos"}
            )

    return render(request, 'portfolio/login.html')


def logoutSite(request):
    logout(request)
    return render(request, 'portfolio/login.html')

def APIs(request):
    return render(request, 'portfolio/api.html')

def projetoFinalDeCurso(request):
    context = {'projetosFinais': ProjetoFinalDeCurso.objects.all()}
    return render(request, 'portfolio/projetoFinalDeCurso.html', context)

portfolio/templates/portfolio/about.html
{% extends 'portfolio/layout.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/about.css' %}">

{% endblock style %}

{% block main %}
<div class="container">
    <div class="Retangulos">
        <div>
            <h1>Alexandre Costa</h1>
            <img src="../../static/portfolio/images/about.png" alt="erro">
        </div>
        <span class="texto">
            Sou o Alexandre Costa, nascido a 20-02-2002 em Lisboa e sou fluente na língua Portuguesa e na língua Inglesa.
            <br><br><br>
            Sou aluno de engenharia Informática do 2º ano da <a
                href="https://www.ulusofona.pt/licenciaturas/engenharia-informatica">Universidade Lusófona</a> em Lisboa.
            <br><br><br>
            Sou uma pessoa bastante preocupada com o outro e alguns exemplos disso são o facto de ser dador de sangue e praticar voluntariado ao longo do ano, mas mais intenso na Época natalícia atraves da associação <a
                href="https://remar.pt/">REMAR</a>.
            <br><br><br>
            Sou jogador de poker por uma equipa profissional (<a href="https://exploit.pt/">exploit</a>) e pratico <a
                href="https://www.zerozero.pt/player.php?id=674224&epoca_id=151">desporto</a> nos tempos livres.
            <br><br><br>
            Podem-me contactar através do <a href="https://www.linkedin.com/in/alexandre-costa-b63347209/">linkedin</a>, <a
                href="https://github.com/alexandre-22007578">Github</a> ou através do email: <b>a22007578@alunos.ulht.pt</b>
            <br><br><br>
            Video Explicativo:
            <iframe src="https://www.youtube.com/embed/HXz5Lglm1rA"></iframe>
        </span>
    </div>


</div>
{% endblock main %}

portfolio/templates/portfolio/api.html
{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/api.css' %}">

{% endblock style %}


<header>
    <div>Alexandre Costa</div>
    <nav>
        <a href="{% url 'portfolio:home'%}">Home</a>
        <a href="{% url 'portfolio:formacao'%}">Formação</a>
        <a href="{% url 'portfolio:projetos'%}">Projetos</a>
        <a href="{% url 'portfolio:projetoFinalDeCurso'%}">Projetos Finais de Curso</a>
        <a href="{% url 'portfolio:web'%}">Programação Web</a>
        <a href="{% url 'portfolio:quizz'%}">Quizz</a>
        <a href="{% url 'portfolio:blog'%}">Blog</a>
        <a href="{% url 'portfolio:about'%}">About</a>
        <a href="{% url 'portfolio:api'%}">APIS</a>

        {% if not user.is_authenticated %}
        <a href="{% url 'portfolio:login'%}">LOGIN</a>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'portfolio:logout'%}">LOGOUT</a>
        {% endif %}

    </nav>
</header>

<head>
    <script>
    setInterval(
    function getTime() {
      const x = document.getElementById("logo_time");
      var today = new Date();
      var date = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
      x.innerHTML = " Neste momento são "  + date.toString() + " horas" + "   ULHT, 2022";
    }, 1000);



    </script>
    <script src="{% static 'portfolio/nome.js' %}"></script>
</head>

{% block main %}
<div class="container">
</div>

<div class="Retangulos">

    <div>
        <p class="titulo">Inspirational Quotes API</p>
        <br>
        <button onclick="get_quote()">click me and get an inspirational quote</button>
        <p id="result"></p>
    </div>
</div>

<div class="Retangulos2">

    <div>
        <p class="titulo">Role the Dice API</p>
        <br>
        <button onclick="get_dice()">click me and role the dice</button>
        <p id="dice"></p>
        <p id="talk"></p>

    </div>
</div>


<div class="Retangulos">
    <div>
        <p class="titulo">weather API</p>
        <br>
        <button onclick="get_weather()">Click to get the information about lisbon's weather</button>


        <p id="Descricao"></p>
        <p id="temperatura"></p>
        <p id="Humidity"></p>
        <p id="precip"></p>
        <p id="sunrise"></p>
        <p id="sunset"></p>


    </div>
</div>


{% endblock main %}

<footer>
    <p id="logo_time">
</footer>

portfolio/templates/portfolio/apresentacao.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/apresentacao.css' %}">

{% endblock style %}

{% block main %}
<div class="container">



</div>
{% endblock main %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/blog.css' %}">

{% endblock style %}

{% block main %}
<div class="container">


    <div class="NEWPOST">

        <div>
            <a href="{% url 'portfolio:nova' %}" class="btn btn-success btn-block">+ Novo Post</a>
        </div>

    </div>
    <br><br><br><br>
    <div class="Retangulos">
        {% for posts in post %}


        <div>

            <b>Post numero:</b> {{posts.id}}
            <br>
            <b>Titulo:</b>{{ posts.titulo }}
            <br>
            <b>Descrição:</b>{{ posts.descrição }}
            <br>
            {% if posts.prioridade == 1 %}
            <b>Prioridade:</b>baixa
            {% endif %}
            {% if posts.prioridade == 2 %}
            <b>Prioridade:</b>media
            {% endif %}
            {% if posts.prioridade == 3 %}
            <b>Prioridade:</b>alta
            {% endif %}
            <br>
            {% if not posts.concluido %}
            <b>Concluida:</b> A realizar
            {% endif %}
            {% if posts.concluido %}
            <b>Concluida:</b> Concluida
            {% endif %}
            <br>
            <b>Data de criação:</b>{{ posts.criado }}
            {% if user.is_authenticated %}
            <a href="{% url 'portfolio:edita' posts.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'portfolio:apaga' posts.id %}" class="btn btn-warning" style="margin-left:80%;">Apagar</a>
            {% endif %}
            <br>
        </div>

        {% endfor %}
    </div>


</div>

{% endblock main %}

portfolio/templates/portfolio/competencias.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/competencias.css' %}">

{% endblock style %}

{% block main %}
<div class="container">



</div>
{% endblock main %}

portfolio/templates/portfolio/edita.html
{% extends 'portfolio/layout.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/about.css' %}">

{% endblock style %}

{% block main %}
<h3>Edit your post here !</h3>
    <form action="{% url 'portfolio:edita' Post_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >

    </form>

{% endblock %}

portfolio/templates/portfolio/formacao.html
{% extends 'portfolio/layout.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/formacao.css' %}"/>

{% endblock style %}


{{% block main %}

<div class="container">
    <a href="#1ano">1ano</a>
    <br>
    <a href="#2ano">2ano</a>
    <br>
    <a href="#3ano">3ano</a>
    <br> <br> <br>

    {% if user.is_authenticated %}

        <div class="Retangulos2">
        <div>

            <a href="https://projeto-final-pw22007578.herokuapp.com/admin/portfolio/cadeira/add/"> <b>Introduzir
                uma nova cadeira</b></a>
        </div>
    </div>
    {% endif %}

    <h1 id="1ano">1ªano</h1>

    Frequentado no ano letivo 2020/2021
    <br>
    <p></p>

    <h2>1ºsemestre</h2>

    <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 1 and cadeira.semestre == 1%}

        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>

    <h2>2 semetre</h2>

     <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 1 and cadeira.semestre == 2%}


        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>


    <h1 id="2ano">2ªano</h1>

    Frequentado no ano letivo 2021/2022
    <br>
    <p></p>

    <h2>1ºsemestre</h2>

    <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 2 and cadeira.semestre == 1%}

        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>

    <h2>2 semetre</h2>

    <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 2 and cadeira.semestre == 2%}

        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>

        <h1 id="3ano">3ªano</h1>

    Frequentado no ano letivo 2022/2023
    <br>
    <p></p>

    <h2>1ºsemestre</h2>

    <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 3 and cadeira.semestre == 1%}

        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>

    <h2>2 semetre</h2>

    <div class="Retangulos">


        {% for cadeira in cadeiras %}

        {% if cadeira.ano == 3 and cadeira.semestre == 2%}

        <div class="texto">

            <li><b>{{cadeira.nome}}</b></li>
            <li>Creditos:<span class="ECTS">({{cadeira.creditos}} ECTS)</span></li>
            <li>rank (1-5): {{cadeira.rank}}🌟</li>
            <li>professores:
                {% for professor in cadeira.professores.all %}
                <ol>
                    {{professor.nome}}
                    <a href="{{professor.link}}">INFO</a>
                </ol>

            </li>
            {% endfor %}
            <li>
                <a href="{{cadeira.link}}">{{cadeira.nome}}</a>
            </li>
            {% if not cadeira.projetos == null %}

            <li>Projetos:
                <ol><a href="projetos">{{cadeira.projetos.nome}}</a></ol>
            </li>
            {% endif %}
            {% if cadeira.projetos == null %}

            <li>Projetos:
                <ol>Nesta cadeira não foi realizado nenhum projeto final</a></ol>
            </li>

            {% endif %}
        </div>
        {% endif %}
        {% endfor %}


    </div>


</div>


{% endblock main %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/home.css' %}">

{% endblock style %}

{% block main %}
<div class="container">



</div>
{% endblock main %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/layout.css' %}"/>

    {% block style %}
    {% endblock style %}
    <script>
    setInterval(
    function getTime() {
      const x = document.getElementById("logo_time");
      var today = new Date();
      var date = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
      x.innerHTML = " Neste momento são "  + date.toString() + " horas" + "   ULHT, 2022";
    }, 1000);




    </script>

</head>
<body>

<header>
    <div>Alexandre Costa</div>
    <nav>
        <a href="{% url 'portfolio:home'%}">Home</a>
        <a href="{% url 'portfolio:formacao'%}">Formação</a>
        <a href="{% url 'portfolio:projetos'%}">Projetos</a>
        <a href="{% url 'portfolio:projetoFinalDeCurso'%}">Projetos Finais de Curso</a>
        <a href="{% url 'portfolio:web'%}">Programação Web</a>
        <a href="{% url 'portfolio:quizz'%}">Quizz</a>
        <a href="{% url 'portfolio:blog'%}">Blog</a>
        <a href="{% url 'portfolio:about'%}">About</a>
        <a href="{% url 'portfolio:api'%}">APIS</a>

        {% if not user.is_authenticated %}
        <a href="{% url 'portfolio:login'%}">LOGIN</a>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'portfolio:logout'%}">LOGOUT</a>
        {% endif %}

    </nav>
</header>
<main>
    {% block main %}

    {% endblock main %}

</main>
<footer>
    <p id="logo_time">
</footer>

</body>
</html>

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/login.css' %}">

{% endblock style %}

{% block main %}
<div class="container">

    <form action="{% url 'portfolio:login' %}" method="post">
        {% csrf_token %}

        <p>Introduza o seu username: <input type="text" name="username" placeholder="Username"></p>
        <p>Introduza a sua password: <input type="password" name="password" placeholder="Password"></p>

        <input type="submit" value="Autenticar!" class="btnSubmit">
    </form>
    {% if message %}
    {{ message }}
    {% endif %}

</div>

{% endblock main %}